### PR TITLE
ensure walk functions return before FastWalk exits; fixes #22

### LINKED ISSUE #22: fastwalk: execution of walk function after FastWalk returns
I don't believe this has been a noticeable issue for most, due to how they use fastwalk (outside of this library, and how fastwalk is used in the stdlib).

As no checking is done to ensure the walk functions have completed, before `FastWalk` exits, it's possible for one of those functions to be exited after it has returned.

This isn't clear, and this can be problematic in a few scenarios. For example:

```go
func someFunc(paths []string) {
    files := make(chan *LocalFile)

    go func() {
		for spath := range paths {
			fastwalk.FastWalk(spath, func(path string, mode os.FileMode) error {
				if mode.IsDir() { return nil }

				files <- &LocalFile{path: path}
				return nil
			})
		}

		close(files)
	}()

	for file := range files {
		// Loop over channel of files here.
    }
}
```

There is simply no way to guarantee that the function being passed in can be concurrency safe. The above will likely cause a `panic: send on closed channel`.

Suggestion: use a `sync.WaitGroup` to ensure all functions return before `FastWalk` returns.

This will mean that if one of the walk functions has a blocking operation, `FastWalk` will wait for it to return, unless that function pushes that blocking operation into a goroutine itself. I believe this is something that should be expected, and seems idiomatic.

PR incoming.

### PR DESCRIPTION
**Pull request by lrstanley**

### CODE REVIEW

**Comment by lrstanley** [comment]
Had a chance to poke, @mattn?

**Comment by mattn** [comment]
Sorry my delay. Thank you.

**Comment by damz** [comment]
This unfortunately broke things badly. It looks like it is now deadlocking itself in some cases. Unfortunately I do not have a clean reproducer, but it ends up with:

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42001447c)
	/usr/lib/golang/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc420014470)
	/usr/lib/golang/src/sync/waitgroup.go:129 +0x72
github.com/mattn/go-zglob/fastwalk.FastWalk(0xc4200142ac, 0x4, 0xc42007e390, 0x50f160, 0xc420136020)
	$GOPATH/src/github.com/mattn/go-zglob/fastwalk/fastwalk.go:102 +0x755
github.com/mattn/go-zglob.glob(0x4fbc92, 0x10, 0xc42004bd00, 0x4b33fe, 0xc42004bd18, 0xc420018100, 0xc420018100, 0x10)
	$GOPATH/src/github.com/mattn/go-zglob/zglob.go:141 +0x143
github.com/mattn/go-zglob.Glob(0x4fbc92, 0x10, 0x449afd, 0x4da3a0, 0x0, 0x12de0, 0x5ad180)
	$GOPATH/src/github.com/mattn/go-zglob/zglob.go:119 +0x3a
main.main()
	$GOPATH/test-tail.go:13 +0x84

goroutine 5 [chan send]:
github.com/mattn/go-zglob/fastwalk.(*walker).doWork(0xc42007e3c0, 0xc420014470)
	$GOPATH/src/github.com/mattn/go-zglob/fastwalk/fastwalk.go:131 +0x95
created by github.com/mattn/go-zglob/fastwalk.FastWalk
	$GOPATH/src/github.com/mattn/go-zglob/fastwalk/fastwalk.go:76 +0x22b

goroutine 8 [chan send]:
github.com/mattn/go-zglob/fastwalk.(*walker).doWork(0xc42007e3c0, 0xc420014470)
	$GOPATH/src/github.com/mattn/go-zglob/fastwalk/fastwalk.go:131 +0x95
created by github.com/mattn/go-zglob/fastwalk.FastWalk
	$GOPATH/src/github.com/mattn/go-zglob/fastwalk/fastwalk.go:76 +0x22b
exit status 2
```

**Comment by lrstanley** [comment]
Can you provide the code that is using FastWalk/z-glob? What Go version/environment? Even if it's not clear, it may still be helpful.

I've been using this for awhile now, and haven't seen any deadlocks, so curious what's different about your environment. I have a feeling it may be related to locking inside of the function that's being passed in, but it looks like you're using z-glob directly. I tested only FastWalk, not much the z-glob implementation of it.

I'll see if I can reproduce when I get home. Looking at the changes I made, I don't see a situation where it could happen, but there may be some special cases with `defer`'s and channels (as I'm using `defer wg.Wait()`)

**Comment by damz** [comment]
@lrstanley As I said, I do not have a clean reproducer. The code that triggers that is essentially:

```
zglob.Glob("/tmp/**/test.txt")
```

The current state of my `/tmp` folder triggers that very reliably, but not always, so this definitely looks like a race condition.

**Comment by damz** [comment]
Actually, this reproduces it reliably, it obviously has to do with the error path:

```golang
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"

	"github.com/mattn/go-zglob"
)

func main() {
	dir, err := ioutil.TempDir("", "example")
	if err != nil {
		log.Fatal(err)
	}
	defer os.RemoveAll(dir)

	for i := 0; i < 100; i++ {
		os.Mkdir(fmt.Sprintf("%s/test%d", dir, i), 0000)
	}

	matches, err := zglob.Glob(dir + "/**/test.txt")

	log.Printf("Matches: %#v", matches)
}
```

**Comment by lrstanley** [comment]
Hmm, ok, thanks. I'll submit a fix when I get home in a couple of hours.

**Comment by lrstanley** [comment]
Super sorry for the delay, new job has been crazy. See https://github.com/mattn/go-zglob/pull/24 for fixes.

**Pull request merged**
